### PR TITLE
Reinstate prev next btns

### PR DESCRIPTION
**Pull request by fidoogle**
Beginning of putting a pagination component together

### CODE REVIEW

**Comment by mcortez1497** [comment]
If I understand correctly - the "Prev/Next" buttons reinstated here are for the demo only, because they just simulate new data for the `table` to display. As it is now, these buttons don't make sense to be in the `rs.data.grid.html` template. We should do one of two things:

1. Move these buttons into the `demo/index.html` and have the demo controller be able to request new data. This way, the buttons are not part of the template and are just for the demo, which is what they seem to be.
2. Move these buttons into an actual pagination directive. The commit message says that these buttons are the start of a pagination directive, so if they are, we should put them in a very bare pagination directive that behaves and interacts the same way to other directives (`tables`, `facets`) do.

Whichever one you choose is up to your discretion @fidoogle, you'd know which one is easiest to implement now. I just want to get this to an organized, releasable state. And we can't add more things like this that don't make sense in the component.

**Comment by fidoogle** [comment]
I probably need to start 'stashing' instead of 'committing'. That will keep these tidbits out and viewable only by me. Thanks for the nudge.

**Comment by mcortez1497** [comment]
It's perfectly fine to commit, that's the only way to get other people's eyes looking at it!

**Comment by fidoogle** [comment]
Got it. Committing is not too bad.

**Comment by davismartin** [comment]
closing merged in another PR

**Pull request closed without merging**
